name: terraform-ci
on:
  pull_request:
    branches: [ "main" ]

jobs:
  fmt-validate-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform FMT (check style)
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (save binary)
        env:
          AWS_ACCESS_KEY_ID: FAKEKEY
          AWS_SECRET_ACCESS_KEY: FAKESECRET
          AWS_DEFAULT_REGION: us-east-1
          AWS_EC2_METADATA_DISABLED: "true"
        run: terraform plan -no-color -out=tfplan.bin -var="owner=NShetty"



      - name: Terraform Show → plan.txt
        run: terraform show -no-color tfplan.bin | tee plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-NShetty
          path: infra/plan.txt

      - name: Extract plan summary (last 20 lines)
        id: extract
        run: |
          SUMMARY=$(tail -n 20 plan.txt)
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment plan summary on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Terraform plan summary** — run #${{ github.run_number }}
            ```terraform
            ${{ steps.extract.outputs.summary }}
            ```
